name: Download OUAT Forecast

on:
  push:
    branches:
      - dev
  workflow_dispatch:
  schedule:
    - cron: '0 0 */10 * *' # Runs every 2 hours

jobs:
  download-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Use Node.js 
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: yarn

      - name: Run the script
        run: npx ts-node src/crons/ouat.ts

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update ouat JSON'
